org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
parchment_mappings_version=[VERSIONED]
parchment_mappings_mc_version=[VERSIONED]
minecraft_version_range=[VERSIONED]
neo_version=[VERSIONED]
loader_version_range=[1,)
mod_id=tillitbreaks
mod_name=Till It Breaks Updated
mod_license=MIT
mod_version=1.0.1
mod_group_id=me.pajic.tillitbreaks
mod_authors=Schauweg, pajic
mod_description=Displays the durability of items on the item itself, updated for 1.21
yacl_version=[VERSIONED]
accessories_version=[VERSIONED]