org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
loader_version=0.16.14
parchment_version=[VERSIONED]
mod_version=1.0.0
maven_group=me.pajic
archives_base_name=till-it-breaks
fabric_version=[VERSIONED]
modmenu_version=[VERSIONED]
yacl_version=[VERSIONED]

accessories_version=[VERSIONED]
accessorify_version=[VERSIONED]
fzzy_version=[VERSIONED]
owo_version=[VERSIONED]
nyfsquiver_version=[VERSIONED]