org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=tillitbreaks
mod.name=Till It Breaks Updated
mod.group=me.pajic
mod.version=1.1.4
mod.channel_tag=
mod.authors=Schauweg, pajic
mod.contributors=
mod.license=MIT
mod.description=Displays the durability of items on the item itself, updated for 1.21 and above
mod.sources_url=https://github.com/pajicadvance/TillitBreaks
mod.homepage_url=https://modrinth.com/mod/till-it-breaks-updated
mod.issues_url=https://github.com/pajicadvance/TillitBreaks/issues
mod.discord_url=https://discord.gg/5RkzS66zWb

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.modmenu=[VERSIONED]
deps.fzzy_config=[VERSIONED]
deps.tool_pouch=[VERSIONED]

publish.modrinth=GG12dlQh
publish.curseforge=1099394
publish.github=false
